server:
  port: 8848
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

Spring:
  redis:
    database: 2
    host: 116.205.136.30
    port: 6379
    password: "*&tbguat65R&R^&76hdsfisy85&^%&$f29r67"

# 日志配置
logging:
  config: classpath:logback.xml
  level:
    com.fetch: debug
    org.springframework: warn

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.fetch.**.domain
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  profiles:
    active: druid
  main:
    log-startup-info: true
    log-for-missing-config: true
